<div class="row">
   <div class="col-xs-12">
      <div class="row" id="indexcontent">
         <div class="col-xs-12">
            <div style="float:right;margin-right:25px;">
               <a class="btn btn-small btn-primary" href="<?php echo $this->httphost; ?>care/docs">Add File</a>
            </div>
            <h3 class="header smaller lighter blue">Files List</h3>
				<?php if($this->docsfile) { $inc = 1;  ?><br>
					<div class="row">
					 <table width="98%" class="table table-striped table-bordered table-hover">
						  <thead>
							 <tr>
								<th class="center">Si.no</th>
								<th class="center">Uploaded File</th>
								<th class="center">Description</th>
								<th class="center">Date</th>
							 </tr>
						  </thead>
						  <tbody>
								<?php foreach ($this->docsfile as $mkey=>$user){  ?>
								<tr>
									<td><?php echo $inc; ?></td>
									<td>
										<a href="<?php echo $this->uphttphost.'html/images/category/'.$user->upfile; ?>" target="_blank">
											<img src="<?php echo $this->uphttphost.'html/images/category/'.$user->upfile; ?>" style="height:75px;width:75px;"/>
										</a>
									</td>
									<td><?php echo $user->content; ?></td>
									<td><?php echo date('d-m-Y h:i A', strtotime($user->created)); ?></td>
								</tr>
							<?php $inc++; } ?>
						  </tbody>
					   </table>
					</div>
               <?php }  else { ?>
				 <div class="row"><br><br>
					<div class="col-sm-12">
					<div class="alert alert-danger">
					   <strong> Files not found</strong>  
					</div>
					</div>
				</div>				 
				 <?php }  ?>
         </div>
      </div>
   </div>
</div>