<?php
 #Getting Objects
 $commonobj = new Default_Models_Common();
?>
<div class="row">
   <div class="col-xs-12">
      <!-- PAGE CONTENT BEGINS -->							
      <div class="row" id="indexcontent">
         <div class="col-xs-12">
		  <div style="float:right;margin-right:25px;">
               <a class="btn btn-small btn-primary" href="<?php echo $this->httphost; ?>employees/index">Back</a>
            </div>
            <h3 class="header smaller lighter blue">History</h3>
				<?php if($this->wellnessinfo) { $inc = 1;  ?><br>
				
					<div class="row">
					 <table width="98%" class="table table-striped table-bordered table-hover">
						  <thead>
							 <tr>
								<th class="center">Si. No</th>
								<th class="center">Date Time</th>
								<th class="center">Body Temperature</th>
								<th class="center">Blood Pressure</th>
								<th class="center">Glucose</th>
								<th class="center">Heart Rate</th>
								<th class="center">Oxygen Saturation</th>
									<th class="center">Asthma</th>
							 </tr>
						  </thead>
						  <tbody>
							<?php foreach ($this->wellnessinfo as $mkey=>$infohis){  
							$infohis = json_encode($infohis);
							$infohis = json_decode($infohis, true);
							$infohismsg = $commonobj->getwellnessMessage($infohis);
							?>
							<tr>
								<td><?php echo $inc;?></td>
								<td><?php echo date('d-m-Y h:i A', strtotime($infohis['created'])); ?></td>
								<td><?php echo $infohismsg['bodytemp']; ?></td>
								<td><?php echo $infohismsg['bp1']; ?></td>
								<td><?php echo $infohismsg['Glucose']; ?></td>
								<td><?php echo $infohismsg['hartrate']; ?></td>
								<td><?php echo $infohismsg['oxygen']; ?></td>
									<td><?php echo $infohismsg['Asthma']; ?></td>
							</tr>
							<?php $inc++; } ?>
						  </tbody>
					   </table>
					</div>
               <?php }  else { ?>
				 <div class="row"><br><br>
					<div class="col-sm-12">
					<div class="alert alert-danger">
					   <strong> History not found</strong>  
					</div>
					</div>
				</div>				 
				 <?php }  ?>
            
         </div>
      </div>
      <!-- PAGE CONTENT ENDS -->
   </div>
   <!-- /.col -->
</div>