<div class="row">
   <div class="col-xs-12">
      <!-- PAGE CONTENT BEGINS -->							
      <div class="row" id="indexcontent">
         <div class="col-xs-12">
            <div style="float:right;margin-right:25px;">
               <a class="btn btn-small btn-primary" href="<?php echo $this->httphost; ?>employees/new"><?php echo $this->translate('Add Employee');?></a>
            </div>
            <h3 class="header smaller lighter blue"><?php echo "Employees List";?></h3>
            <!-- message div-->		
            
			<?php if($this->msg) { ?>
			<div class="row">
				<div class="alert alert-block alert-success">
				   <button type="button" class="close" data-dismiss="alert">
						<i class="ace-icon fa fa-times"></i>
				   </button>
				   <i class="ace-icon fa fa-check green"></i>
				   <strong class="green">
					<?php echo $this->msg; ?>
				   </strong>  
				</div>
			</div>
			<?php } ?>
				<?php if($this->employees) { $inc = 1;  ?><br>
				
					<div class="row">
					 <table width="98%" class="table table-striped table-bordered table-hover">
						  <thead>
							 <tr>
								<th class="center">Si.no</th>
								<th class="center">Employee Id</th>
								<th class="center">Fullname</th>
								<th class="center">Aadhar</th>
								<th class="center">Email</th>
								<th class="center">Action</th>
							 </tr>
						  </thead>
						  <tbody>
								<?php foreach ($this->employees as $mkey=>$user){ 
								 ?>
								<tr>
									<td><?php echo $inc; ?></td>
									<td><?php echo str_pad($user->uid, 5, 0, STR_PAD_LEFT); ?></td>
									<td><?php echo ucfirst($user->firstname)." ".$user->lastname; ?></td>
									<td><?php echo $user->aadhar; ?></td>
									<td><?php echo $user->email; ?></td>
									<td>						 
										<a title="Click to remove" class="red" href="<?php echo $this->httphost; ?>employees/delete/rowid/<?php echo $user->uid; ?>" onclick="return confirm('Are you sure to remove?');">
											<i class="ace-icon fa fa-trash-o bigger-130"></i>
										</a> &nbsp;&nbsp;&nbsp;					 
										<a title="Edit" class="blue" href="<?php echo $this->httphost; ?>employees/edit/rowid/<?php echo $user->uid; ?>">
											<i class="ace-icon fa fa-pencil bigger-130 fa-lg"></i>
										</a>&nbsp;&nbsp;&nbsp;					 
										<a title="Status" class="blue" href="<?php echo $this->httphost; ?>employees/status/rowid/<?php echo $user->adminid; ?>">
											<i class="ace-icon fa fa-heart bigger-130 fa-lg" style="color: green;"></i>
										</a> &nbsp;&nbsp;&nbsp;					 
										<a title="History" class="blue" href="<?php echo $this->httphost; ?>employees/history/rowid/<?php echo $user->adminid; ?>">
											<i class="ace-icon fa fa-search bigger-130 fa-lg"></i>
										</a>	&nbsp;&nbsp;&nbsp;					 
										<a title="Attach Docs" class="blue" href="<?php echo $this->httphost; ?>employees/docslist/rowid/<?php echo $user->adminid; ?>">
											<i class="ace-icon fa fa-upload bigger-130 fa-lg"></i>
										</a>						
									</td>
								</tr>
							<?php $inc++; } ?>
						  </tbody>
					   </table>
					</div>
               <?php }  else { ?>
				 <div class="row"><br><br>
					<div class="col-sm-12">
					<div class="alert alert-danger">
					   <strong> Employees not found</strong>  
					</div>
					</div>
				</div>				 
				 <?php }  ?>
            
         </div>
      </div>
      <!-- PAGE CONTENT ENDS -->
   </div>
   <!-- /.col -->
</div>