<div class="row">
   <div class="col-xs-12">
      <div class="row" id="indexcontent">
         <div class="col-xs-12">
            <h3 class="header smaller lighter blue">Sent Notification List</h3>
				<?php if($this->docsfile) { $inc = 1;  ?><br>
					<div class="row">
					 <table width="98%" class="table table-striped table-bordered table-hover">
						  <thead>
							 <tr>
								<th class="center">Si.no</th>
								<th class="center">Notification Content</th>
								<th class="center">Docs</th>
							 </tr>
						  </thead>
						  <tbody>
								<?php foreach ($this->docsfile as $mkey=>$user){  ?>
								<tr>
									<td><?php echo $inc; ?></td>
									<td>
										<b><?php echo date('d-m-Y h:i A', strtotime($user->created)); ?></b><br>
										<hr style="margin:0px;">
										<?php echo $user->content; ?>
									</td>
									<td>
										<?php if(!empty($user->upfile)) { ?>
										<a href="<?php echo $this->uphttphost.'html/images/category/'.$user->upfile; ?>" target="_blank">
											<img src="<?php echo $this->uphttphost.'html/images/category/'.$user->upfile; ?>" style="height:75px;width:75px;"/>
										</a><br>
										<?php } ?>
									</td>
								</tr>
							<?php $inc++; } ?>
						  </tbody>
					   </table>
					</div>
               <?php }  else { ?>
				 <div class="row"><br><br>
					<div class="col-sm-12">
					<div class="alert alert-danger">
					   <strong> Notification not found</strong>  
					</div>
					</div>
				</div>				 
				 <?php }  ?>
         </div>
      </div>
   </div>
</div>